sources:
  - name: threshold-tbtc-sepolia
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/59264/threshold-tbtc-sepolia/version/latest
    transforms:
      - autoPagination:
          limitOfRecords: 2000
plugins:
  - pollingLive:
      defaultInterval: 1000
documents:
  - ./src/pages/query.graphql